# Curse of dimensionality
## Alvaro Esquivel 11002822

In [1]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [3]:
X = np.arange(10).reshape(5, 2)
print(X)

poly = PolynomialFeatures(2)
poly.fit_transform(X)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.],
       [ 1.,  6.,  7., 36., 42., 49.],
       [ 1.,  8.,  9., 64., 72., 81.]])

In [12]:
poly = PolynomialFeatures(3)
dim_poly = poly.fit_transform(X)
print(dim_poly, "\nDimencionalidad:", dim_poly.shape)

[[  1.   0.   1.   0.   0.   1.   0.   0.   0.   1.]
 [  1.   2.   3.   4.   6.   9.   8.  12.  18.  27.]
 [  1.   4.   5.  16.  20.  25.  64.  80. 100. 125.]
 [  1.   6.   7.  36.  42.  49. 216. 252. 294. 343.]
 [  1.   8.   9.  64.  72.  81. 512. 576. 648. 729.]] 
Dimencionalidad: (5, 10)


In [11]:
poly = PolynomialFeatures(6)
dim_poly = poly.fit_transform(X)
print(dim_poly, "\nDimencionalidad:", dim_poly.shape)

[[1.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00
  0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00
  0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00
  0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00
  0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00]
 [1.00000e+00 2.00000e+00 3.00000e+00 4.00000e+00 6.00000e+00 9.00000e+00
  8.00000e+00 1.20000e+01 1.80000e+01 2.70000e+01 1.60000e+01 2.40000e+01
  3.60000e+01 5.40000e+01 8.10000e+01 3.20000e+01 4.80000e+01 7.20000e+01
  1.08000e+02 1.62000e+02 2.43000e+02 6.40000e+01 9.60000e+01 1.44000e+02
  2.16000e+02 3.24000e+02 4.86000e+02 7.29000e+02]
 [1.00000e+00 4.00000e+00 5.00000e+00 1.60000e+01 2.00000e+01 2.50000e+01
  6.40000e+01 8.00000e+01 1.00000e+02 1.25000e+02 2.56000e+02 3.20000e+02
  4.00000e+02 5.00000e+02 6.25000e+02 1.02400e+03 1.28000e+03 1.60000e+03
  2.00000e+03 2.50000e+03 3.12500e+03 4.09600e+03 5.12000e+03 6.40000e+03
  8.00000e

## Crecimiento de dimencionalidad utilizando 2 valiables

In [20]:
for i in range(1, 100, 2):
    poly = PolynomialFeatures(i)
    dim_poly = poly.fit_transform(X)
    print("Polinomio:", i, " Dimencionalidad:", dim_poly.shape)

Polinomio: 1  Dimencionalidad: (5, 3)
Polinomio: 3  Dimencionalidad: (5, 10)
Polinomio: 5  Dimencionalidad: (5, 21)
Polinomio: 7  Dimencionalidad: (5, 36)
Polinomio: 9  Dimencionalidad: (5, 55)
Polinomio: 11  Dimencionalidad: (5, 78)
Polinomio: 13  Dimencionalidad: (5, 105)
Polinomio: 15  Dimencionalidad: (5, 136)
Polinomio: 17  Dimencionalidad: (5, 171)
Polinomio: 19  Dimencionalidad: (5, 210)
Polinomio: 21  Dimencionalidad: (5, 253)
Polinomio: 23  Dimencionalidad: (5, 300)
Polinomio: 25  Dimencionalidad: (5, 351)
Polinomio: 27  Dimencionalidad: (5, 406)
Polinomio: 29  Dimencionalidad: (5, 465)
Polinomio: 31  Dimencionalidad: (5, 528)
Polinomio: 33  Dimencionalidad: (5, 595)
Polinomio: 35  Dimencionalidad: (5, 666)
Polinomio: 37  Dimencionalidad: (5, 741)
Polinomio: 39  Dimencionalidad: (5, 820)
Polinomio: 41  Dimencionalidad: (5, 903)
Polinomio: 43  Dimencionalidad: (5, 990)
Polinomio: 45  Dimencionalidad: (5, 1081)
Polinomio: 47  Dimencionalidad: (5, 1176)
Polinomio: 49  Dimencional

## Crecimiento utilizando  4 variables

In [21]:
X = np.arange(8).reshape(2, 4)
print(X)

[[0 1 2 3]
 [4 5 6 7]]


In [22]:
for i in range(1, 100, 2):
    poly = PolynomialFeatures(i)
    dim_poly = poly.fit_transform(X)
    print("Polinomio:", i, " Dimencionalidad:", dim_poly.shape)

Polinomio: 1  Dimencionalidad: (2, 5)
Polinomio: 3  Dimencionalidad: (2, 35)
Polinomio: 5  Dimencionalidad: (2, 126)
Polinomio: 7  Dimencionalidad: (2, 330)
Polinomio: 9  Dimencionalidad: (2, 715)
Polinomio: 11  Dimencionalidad: (2, 1365)
Polinomio: 13  Dimencionalidad: (2, 2380)
Polinomio: 15  Dimencionalidad: (2, 3876)
Polinomio: 17  Dimencionalidad: (2, 5985)
Polinomio: 19  Dimencionalidad: (2, 8855)
Polinomio: 21  Dimencionalidad: (2, 12650)
Polinomio: 23  Dimencionalidad: (2, 17550)
Polinomio: 25  Dimencionalidad: (2, 23751)
Polinomio: 27  Dimencionalidad: (2, 31465)
Polinomio: 29  Dimencionalidad: (2, 40920)
Polinomio: 31  Dimencionalidad: (2, 52360)
Polinomio: 33  Dimencionalidad: (2, 66045)
Polinomio: 35  Dimencionalidad: (2, 82251)
Polinomio: 37  Dimencionalidad: (2, 101270)
Polinomio: 39  Dimencionalidad: (2, 123410)
Polinomio: 41  Dimencionalidad: (2, 148995)
Polinomio: 43  Dimencionalidad: (2, 178365)
Polinomio: 45  Dimencionalidad: (2, 211876)
Polinomio: 47  Dimencionalida

## Utilizando 8 variables

In [23]:
X = np.arange(16).reshape(2, 8)
print(X)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [25]:
for i in range(1, 46, 2):
    poly = PolynomialFeatures(i)
    dim_poly = poly.fit_transform(X)
    print("Polinomio:", i, " Dimencionalidad:", dim_poly.shape)

Polinomio: 1  Dimencionalidad: (2, 9)
Polinomio: 3  Dimencionalidad: (2, 165)
Polinomio: 5  Dimencionalidad: (2, 1287)
Polinomio: 7  Dimencionalidad: (2, 6435)
Polinomio: 9  Dimencionalidad: (2, 24310)
Polinomio: 11  Dimencionalidad: (2, 75582)
Polinomio: 13  Dimencionalidad: (2, 203490)
Polinomio: 15  Dimencionalidad: (2, 490314)
Polinomio: 17  Dimencionalidad: (2, 1081575)
Polinomio: 19  Dimencionalidad: (2, 2220075)
Polinomio: 21  Dimencionalidad: (2, 4292145)
Polinomio: 23  Dimencionalidad: (2, 7888725)
Polinomio: 25  Dimencionalidad: (2, 13884156)
Polinomio: 27  Dimencionalidad: (2, 23535820)
Polinomio: 29  Dimencionalidad: (2, 38608020)
Polinomio: 31  Dimencionalidad: (2, 61523748)
Polinomio: 33  Dimencionalidad: (2, 95548245)
Polinomio: 35  Dimencionalidad: (2, 145008513)
Polinomio: 37  Dimencionalidad: (2, 215553195)
Polinomio: 39  Dimencionalidad: (2, 314457495)
Polinomio: 41  Dimencionalidad: (2, 450978066)
Polinomio: 43  Dimencionalidad: (2, 636763050)
Polinomio: 45  Dimenci