## XOR como composicion
### Álvaro Andres Esquivel Gómez 11002822

In [1]:
import numpy as np

In [3]:
def operacion_not(x1):
    parametros = [-1, 1]
    
    return int(x1 * parametros[0] + parametros[1])

test = 1

operacion_not(test)

0

In [7]:
def operacion_or(x1, x2):
    parametros = [1, 1, 0]
    
    return int((x1 * parametros[0]) + (x2 * parametros[1]) + parametros[2] > 0)

testx1 = 0
testx2 = 0

operacion_or(testx1, testx2)

0

In [12]:
def operacion_and(x1, x2):
    parametros = [1, 1, -1]
    
    return int((x1 * parametros[0]) + (x2 * parametros[1]) + parametros[2] > 0)

testx1 = 1
testx2 = 1

operacion_and(testx1, testx2)

1

In [17]:
def operacion_xor(x1, x2):
    temp_and = operacion_and(x1, x2)
    temp_or = operacion_or(x1, x2)
    
    nand_temp = operacion_not(temp_and)
    
    temp_resultado = operacion_and(nand_temp, temp_or)
    
    return temp_resultado

testx1 = 0
testx2 = 1

operacion_xor(testx1, testx2)

1

## Utilizando perceptrones entrenados.

In [13]:
def op_or(val1, val2):
    #Operacion con valores entrenados
    resultado = (val1 * 2) + (val2 * 2) - 1
    print(resultado)
    #Operacion sigmoid
    sigmoid = 1/(1 + np.exp(-resultado))
    print(sigmoid)
    return np.round(sigmoid, 0)

v1 = np.array([0, 0, 1, 1])
v2 = np.array([0, 1, 0, 1])
# Resultado esperado 0 1 1 1

op_or(v1, v2)

[-1  1  1  3]
[0.26894142 0.73105858 0.73105858 0.95257413]


array([0., 1., 1., 1.])

In [19]:
def op_and(val1, val2):
    #Operacion con valores entrenados
    resultado = (val1 * 2) + (val2 * 2) - 3
    print(resultado)
    #Operacion sigmoid
    sigmoid = 1/(1 + np.exp(-resultado))
    print(sigmoid)
    return np.round(sigmoid, 0)

v1 = np.array([0, 0, 1, 1])
v2 = np.array([0, 1, 0, 1])
# Resultado esperado 0 0 0 1

op_and(v1, v2)

[-3 -1 -1  1]
[0.04742587 0.26894142 0.26894142 0.73105858]


array([0., 0., 0., 1.])